SELECT COUNT(*) FROM Trip WHERE Emp_ID IN (SELECT ID FROM Employee WHERE Dept = 'Marketing');
SELECT DISTINCT Name FROM Employee WHERE ID IN (SELECT Emp_ID FROM Trip WHERE ID NOT IN (SELECT Trip_ID FROM Expense));
SELECT Contact FROM Dept WHERE Code IN (SELECT Dept FROM Employee WHERE ID IN (SELECT Emp_ID from Trip WHERE Est_Cost IN (SELECT Max(Est_Cost) FROM Trip)));
SELECT Name FROM Dept WHERE Code NOT IN (SELECT Dept FROM Employee WHERE ID IN (SELECT Emp_ID FROM Trip));
SELECT DISTINCT To_City FROM Trip WHERE Est_Cost = (SELECT Avg(Est_Cost) FROM Trip);
